### PR TITLE
Made crafting obey remaining items, and added some non-working recipes.

### PR DESCRIPTION
**Pull request by avixk**
I use this fork on my server, and so I added a few things that I wanted. Remaining crafting items (like bottles from crafting honey blocks) are now respected, they will be put into the output container along with the crafted item.

Also firework crafting and shulker dyeing did not work, so I added a few recipes to fix it.

### CODE REVIEW

**Comment by MrTransistorsChannel** [comment]
Ok I`ll test your fix tomorrow, seems working to me. Also the recipe for FW rockets with flight duration 1 was added in 1.17 so it can be removed to avoid recipe duplication.

**Comment by avixk** [comment]
> Ok I`ll test your fix tomorrow, seems working to me. Also the recipe for FW rockets with flight duration 1 was added in 1.17 so it can be removed to avoid recipe duplication.

"Creative" rockets can be crafted without the added recipes, but flight duration 1 2 and 3 cannot be.

**Comment by MrTransistorsChannel** [comment]
> > Ok I`ll test your fix tomorrow, seems working to me. Also the recipe for FW rockets with flight duration 1 was added in 1.17 so it can be removed to avoid recipe duplication.
> 
> "Creative" rockets can be crafted without the added recipes, but flight duration 1 2 and 3 cannot be.

"Creative" rockets are the same as 1 flight duration, just without the nbt. The only problem with this is that they cannot be stacked together, which in my opinion is not a big deal because if a person is going to build a rocket crafter, he probably won`t need to make them manually anymore. 
Other solution may be force adding nbt to rockets without it.

I`m not sure about the consequences of a recipe duplication

I will test your fork and see if there are any problems with it.

**Comment by avixk** [comment]
> > > Ok I`ll test your fix tomorrow, seems working to me. Also the recipe for FW rockets with flight duration 1 was added in 1.17 so it can be removed to avoid recipe duplication.
> > 
> > 
> > "Creative" rockets can be crafted without the added recipes, but flight duration 1 2 and 3 cannot be.
> 
> "Creative" rockets are the same as 1 flight duration, just without the nbt. The only problem with this is that they cannot be stacked together, which in my opinion is not a big deal because if a person is going to build a rocket crafter, he probably won`t need to make them manually anymore.
> Other solution may be force adding nbt to rockets without it.
> 
> I`m not sure about the consequences of a recipe duplication
> 
> I will test your fork and see if there are any problems with it.

Are you sure "creative" and flight duration 1 rockets are the same? I tested it and they seemed slightly worse than flight duration 1.

**Comment by MrTransistorsChannel** [comment]
Well, my bad, I always thought they had the same flight durations:)
have just tested and they really are a little bit worse

**Comment by MrTransistorsChannel** [comment]
I`m now rewriting your algorithm into the original source code to save the original project structure and fix some other issues (#7)
Will add custom recipes in a separate update.
I have a different view on how to manage dropping items so it also will be in a separate update

**Comment by MrTransistorsChannel** [comment]
Implemented your method in #8, works fine, waiting for @Fliens to rewiew

**Review by Fliens — APPROVED** [review]

**Comment by Fliens** [comment]
Looks good to me

**Pull request merged**
