### PR TITLE
Reproducible Builds and GitHub Actions

### LINKED ISSUE #15: Reproducible Builds
Ideally we'd have this plugin using either Maven or Gradle so that other people can much more easily build the plugin and contribute. 

I'm happy to set this up, as well as Github Actions which will automatically build and release the project here so there's not as much work needed for other users who want development builds.

### PR DESCRIPTION
**Pull request by hhenrichsen**
## Description
This PR adds a gradle build file and adds GitHub actions to automatically release builds. Closes #15.

## New Features
* Anyone with Java on their system can now easily build this project by running `gradlew jar` (or `./gradlew.bat jar` on Windows).
* If you `git tag` a commit with a version (like 2.3.0, so `git tag 2.3.0`), GitHub will build and release the plugin for you.
* Any other builds are built as a Development Build which isn't shown on the homepage but shows up in the releases tab.
* Badges on the homepage to show if builds are passing/failing.

If you have any questions don't be afraid to reach out to me, I'm `UberPilot#9999` on Discord.

### CODE REVIEW

**Comment by Fliens** [comment]
That's a great idea and looks good to me. But I also don't have much experience with actions and gradle.
@MrTransistorsChannel could you take a look at this aswell please? :)

**Comment by MrTransistorsChannel** [comment]
I'm a little bit busy with my university stuff right now, will check it in a week. I also worked with Gradle just a couple of times so will have to remember everything.

**Comment by hhenrichsen** [comment]
What this does is this means we can build a jar outside of Eclipse/IntelliJ, and it means that we don't have to manually add Spigot/Paper to the libraries of either project. It's not very complex. 

Actions uses this to build the jar right here on GitHub. If you have any questions about what specific things are doing, I'm happy to help explain them.

**Comment by MrTransistorsChannel** [comment]
Ok so I tested Gradle building and it works which is good! The only question: I didn`t find a task for building .jar from console, does that mean that you can only export the jar from an IDE or GitHub?

**Review by MrTransistorsChannel — CHANGES_REQUESTED** [review]
Please add a task to build .jar from console
Everything else is working fine

**Comment by hhenrichsen** [comment]
There's already a task that does this, the `jar` task. From console you can run `gradlew jar`. The GitHub action is using the task to build a jar from console to build the jar.

**Review by MrTransistorsChannel — APPROVED** [review]
Ok, my bad, everything works fine

**Comment by MrTransistorsChannel** [comment]
Waiting for @Fliens

**Pull request merged**
