### PR TITLE
1.17 update

### PR DESCRIPTION
**Pull request by MrTransistorsChannel**
Added support for glow item frames because... maybe people will need it i don't know :)
Updated `api-version` in `plugin.yml`
Updated readme

### Has to be built with Java 16

### CODE REVIEW

**Comment by MrTransistorsChannel** [comment]
I didn`t update the version number so you can do it if you want

**Comment by Fliens** [comment]
That's a good idea
Could you maybe split the Autocraft.jar into multiple methods so that it's easier to read (in a seperate request from this one)

**Comment by MrTransistorsChannel** [comment]
What do you mean by splitting the jar? Did you mean Autocraft.java? If so, am I supposed to split the handleAutocrafter() method into multiple or what?
Also I'll be busy for a couple of days so won't be coding, I'll be back next week

**Comment by Fliens** [comment]
No i just meant that's something that should be done eventually. I'm creating an issue for it :)

**Review by Fliens — APPROVED** [review]

**Pull request merged**
